site_name: System-Modernization.org
theme:
  material


nav:
  - Home: index.md
  - Roadmap: 
    - Overview: roadmap.md
    - Legacy Assessment:
      - Assessment Overview: assessment.md
      - Strategic: strategic.md
      - Functional: functional.md
    -  Modernization Design:
       - Modernization Overview: modernization.md
       - Business Architecture: businessarchitecture.md
       - API Architecture: apiarchitecture.md
       - Data Architecture: dataarchitecture.md
       - Application Architecture: applicationarchitecture.md
       - Technical Architecture: technicalarchitecture.md
  - Techniques:
    - Creating a Product Roadmap: productroadmapcreate.md
    - Identifying Objects In Legacy Code: identifyingobjects.md
  - Technology:
    - Overview: technology.md
    - Tools:
      - Code Assessment:
         - Tool One: toolone.md
  - About: about.md